alias themes="cd /usr/share/themes"
alias icons="cd /usr/share/icons"
alias lthemes="cd $HOME/.themes"
alias licons="cd $HOME/.icons"
alias lbin="cd $HOME/.local/bin"
alias tmp="cd /tmp"
alias shist="history | grep"
alias ealias="nano $HOME/.bash_aliases"
alias ralias="source $HOME/.bash_aliases"
alias edconf="nano $HOME/.bashrc"
alias reconf="source $HOME/.bashrc"

alias bril="cd $HOME/Github/Brilliance"
alias oad="cd $HOME/Github/Azurra_framework"
alias gal="cd $HOME/Pictures/gallery"
alias hub="cd $HOME/Github"
alias docs="cd $HOME/Documents"
alias oadu="cd $HOME/Github/Azurra_framework_upstream"
alias az="cd $HOME/Github/Azurra"

alias GDB="GTK_DEBUG=interactive"
alias gwf='gtk3-widget-factory'

alias ticompress="transimg -o resize -w 1360 -h 768 -e ''"

alias gs="git status"
alias gd="git diff"
alias gp="git pull"
alias gc="git commit -m"
alias ga="git add"
